### ISSUE TITLE
[BUG] RemoteConsoleEndpoint should declare an error handler

### ISSUE THREAD

**Issue by adamretter** [eXist-db/monex#116] opened 2020-01-07 13:53 UTC
```
2019-12-20 12:10:09,656 [Scheduler-982565180-1] WARN  (JsrEvents.java [callError]:158) - Unable to report throwable to websocket (no @OnError handler declared): org.exist.remoteconsole.RemoteConsoleEndpoint
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 36688/10000 ms
```

**Comment by line-o** [comment] 2020-11-11 13:32
duplicate of #128

**Closed by line-o** 2020-11-11 13:32 UTC
Labels: bug, duplicate
