### ISSUE TITLE
Update for compatibility with eXist 5.0.0

### ISSUE THREAD

**Issue by joewiz** [eXist-db/monex#60] opened 2018-08-27 17:54 UTC
According to @adamretter, XML format of JMX in 5.0.0 has changed slightly, and monex's javascript is tightly coupled to old JMX output. 

- [ ] Make parsing of JMX XML more resilient, if one element fails, just ignore and move to the next instead of exploding.
- [ ] Update javascript to use new names for JMX format
- [ ] Extend functionality to report new cache info
- [ ] Write unit tests
- [ ] Write integration tests

**Comment by joewiz** [comment] 2018-09-10 18:03
According to @dizzzz the JMX side is fixed. We still need to test monex.

**Comment by dizzzz** [comment] 2018-09-10 18:15
monex is not yet working :-(

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1700062/45316068-3d883c00-b536-11e8-9221-800a7f8aef16.png">

**Comment by djbpitt** [comment] 2018-10-24 16:02
In 5.0rc4 in Monex 0.9.16 (running on Centos 6) I see:
```
Alert! Connection to server failed. Retrying ...
```
in the "Monitoring (local)" view and no activity. Other views (indexes, profiling, data visualizer) all seem to work.

**Comment by dizzzz** [comment] 2018-10-24 19:43
which java version?

**Comment by djbpitt** [comment] 2018-10-25 06:38
jdk1.8.0_9

**Comment by duncdrum** [comment] 2018-12-11 13:36
integration tests should go into [e2e-core](https://github.com/eXist-db/e2e-core) for now

**Comment by dizzzz** [comment] 2018-12-11 14:03
The issue is not yet fixed; issue 1: as the lock-ing code has been changed, the JMX reporting is not relevant anymore. This can be fixed by adding a condition check for < 5.0.0  issue 2: some cache manager JMX stats are missing; this should not be the case according to @adamretter

**Comment by duncdrum** [comment] 2018-12-16 17:10
see a2c7227f9b80e203615214e50bd8895e5404928b 
manually testing `0.9.17` (installed from public repo) in ` 5.0.0-SNAPSHOT` build `201812151801`
all seems to be working. 
i get a console error on `profiling.html`
```
[Error] ReferenceError: Can't find variable: JMX
	Global Code (exadmin.js:43)
``` 

when enabling the query-tracing on the same page the exist.log contains the following warning
```
16 Dec 2018 17:04:15,426 [qtp1765350920-70] WARN  (IndexKeys.java [eval]:154) - org.exist.storage.structural.NativeStructuralIndexWorker isn't an instance of org.exist.indexing.OrderedIndexWorker. Start value '()' ignored. 
```

**Comment by joewiz** [comment] 2019-05-28 00:15
In my testing just now with the current eXist develop branch (5.0.0-RC8-SNAPSHOT), the remote console pane does not connect to the `/rconsole` endpoint:

> <img width="291" alt="Screen Shot 2019-05-27 at 8 09 29 PM" src="https://user-images.githubusercontent.com/59118/58442770-7d3e8600-80bb-11e9-9e2d-fd021e5b0a9f.png">

> <img width="342" alt="Screen Shot 2019-05-27 at 8 10 05 PM" src="https://user-images.githubusercontent.com/59118/58442777-862f5780-80bb-11e9-95fb-a37bf3f780da.png">

I see that in e2ecore we have @duncdrum's test for the remote console pane, but it seems to only check that the `#status` element is loaded, not that it says `Connected.` See https://github.com/eXist-db/e2e-core/blob/master/cypress/integration/5.x.x/monex_spec.js#L43-L50.

Is anyone else able to load the remote console pane with eXist 5.0.0 snapshot builds?

**Comment by duncdrum** [comment] 2019-05-28 08:54
same here, once we fix `rconsole` we should indeed update he e2e-core test.

**Comment by adamretter** [comment] 2019-05-28 09:49
@joewiz I already discussed the rconsole stuff with @wolfgangmm. I did some preliminary digging and contacted the Jetty team with Wolfgang CC'd on the emails. I believe it was left with him deciding where to place some code for the WebSocket stuff. Perhaps this one fell through the cracks, and needs its own issue?

**Comment by joewiz** [comment] 2019-06-10 13:50
@adamretter As requested by @duncdrum, could you please post the emails?

**Comment by adamretter** [comment] 2019-06-12 15:30
@joewiz and @duncdrum The thread on the `jetty-users` mailing list from 3rd May 2019 starts here - https://www.eclipse.org/lists/jetty-users/msg08893.html

**Comment by wolfgangmm** [comment] 2019-06-16 17:19
Upon further debugging, it looks like jetty is finding the jar and tries to scan it for annotations:

```
2019-06-16 19:13:12,351 [qtp1634411546-25] DEBUG (AnnotationParser.java [parseJarEntry]:916) - Scanning class from jar file:///Users/wolfgang/Source/exist/eXist/exist-distribution/target/exist-distribution-5.0.0-RC8-SNAPSHOT-dir/data/expathrepo/monex-2.0.1/content/monex-2.0.1.jar!/org/exist/remoteconsole/RemoteConsoleEndpoint.class->org/exist/remoteconsole/RemoteConsoleEndpoint.class[0]
```

It does not seem to react on the @ServerEndpoint annotation though. I tried adding `javax.websocket-api` to the poms, but without success so far.

**Comment by wolfgangmm** [comment] 2019-06-17 09:56
For websockets to work in Jetty, some dependencies are missing server-side, in particular `javax.websocket.api`. eXist core only lists `websocket-servlet`, which I think is not even needed if you use the javax annotations.

For now I added the necessary dependencies to monex itself, which works fine with our classloader. We should think about a clean up though and either add the correct jars to core or remove the `websocket-servlet` dependency.

**Comment by line-o** [comment] 2020-04-08 11:31
monex 2.1.1 is compatible with eXist 5.x.x

**Closed by line-o** 2020-04-08 11:31 UTC
Labels: bug, enhancement
